### ISSUE TITLE
wrong defaults in pico-sdk/src/boards/include/boards/adafruit_itsybitsy_rp2040.h

### ISSUE THREAD

**Issue by apbatthrive** [raspberrypi/pico-sdk#1161]
this file specifies:
#define PICO_DEFAULT_I2C 0
But the SDA / SCL pins are 2/3, which is I2C1
See https://learn.adafruit.com/assets/107207

**Comment by dhalbert** [comment]
A PR would be welcome. Thanks!

**Comment by 2bndy5** [comment]
I just ran into this as well. I would prefer the breadboard pins be the default bus (not the stemma connector) because not all devices are guaranteed to have pull-ups and adding pull-ups to the stemma lines... you may as well be using the breadboard pins.

Either way, I can submit a PR. My CI is currently producing faulty artifacts for the itsybitsy build.

**Comment by kilograham** [comment]
merged into develop
