### ISSUE TITLE
clock_configure() doesn't remember the real frequency

### ISSUE THREAD

**Issue by Reneg973** [raspberrypi/pico-sdk#368]
just the input frequency is stored in `configured_freq`.
Therefore please change to:
```
    // Store the configured frequency
    configured_freq[clk_index] = (uint32_t)(((uint64_t) src_freq << 8) / div);
```

**Comment by lurch** [comment]
Your message is lacking context, so I assume you're talking about [this](https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_clocks/clocks.c#L42) function?

Is the concern here the "real frequency" differing from the "requested frequency" because of the 24.8 fractional divider?
Rather than change the line where the `configured_freq` is updated, perhaps it makes sense to add:
```
// Calculate the actual frequency that will be used
freq = (uint32_t) (((uint64_t) src_freq << 8) / div);
```
immediately after https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_clocks/clocks.c#L51 ? :man_shrugging:

**Comment by Reneg973** [comment]
Of course of course, I thought when I write "clock_configure()" as title and there is just one function with this name in the complete SDK, the context is clear? :)
Yes fixing it this way would make it more readable. The result will be the same, namely that clock_get_hz() returns a the frequency which is set
