### ISSUE TITLE
Why pwm_set_wrap's param wrap type in pwm.h  is uint16_t?

### ISSUE THREAD

**Issue by dty717** [raspberrypi/pico-sdk#559]
The pwm_config struct of top type is uint32_t. When setting the value using pwm_set_wrap, the param type is uint16_t.
I don't know the reason.

**Comment by Wren6991** [comment]
Yep, the members of `pwm_config` represent registers, so that the struct can be quickly pushed into and pulled out of hardware registers. The register `pwm_hw->ch[0].top` occupies 32 bits' worth of address space, like all registers on RP2040. Meanwhile the field `TOP`  is only 16 bits in size, which matches the declaration of `pwm_config_set_wrap`.

It wouldn't hurt if the `pwm_config` struct member `top` were 16 bits instead of 32. It probably wouldn't help either, because the other fields would still get 32-bit-aligned, so the struct would be the same size. It's just done this way for consistency.
